spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellozjf/config-repo.git
          username: hellozjf
          password: Zjf@1234
  rabbitmq:
    host: aliyun.hellozjf.com
    port: 5672
    username: hellozjf
    password: Zjf@1234
eureka:
  client:
    service-url:
      defaultZone: http://aliyun.hellozjf.com:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"