server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://aliyun.hellozjf.com:8761/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka